### ISSUE TITLE
Memory - switching between background color/img and appended color/img

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#169]
I'm trying to have the option to have a cover of my "cards" and  on click switch between the color or image that was already appended to the "card" 

``` js
function randomFromTo(from, to) {
  return Math.floor(Math.random() * (to - from + 1) + from);
}
/* randomizes the pick for the cards from the array */
function addColorOrImg(){

 var colorOptions = ["red","red","green","green","purple","purple","yellow","yellow"]

  var optionUsed = [];
/* splice adds and removes options from the array then puts them back in  */
  $("td").each(function(){
        var randomize =  Math.floor(Math.random() * colorOptions.length);
        $(this).append('<style background="' + colorOptions[randomize] + '"/>');
        if (optionUsed.indexOf(colorOptions[randomize] ) != -1) colorOptions.splice(randomize, 1);
        else optionUsed.push(colorOptions[randomize] );
        // console.log(colorOptions)
  });

} addColorOrImg()

function clickCard(){
  var cardAmount = $("td").length

  $("td").click(function(event){
    moves++
    $(".totalmoves").html(moves)
    $(this).css("display", "none")
    num++;
    var cardAttr = $("style.selected").attr("style")
    var id2 = $(this).attr("style");
    $(this).addClass("selected") /* need "this" to select indv cells*/

  })
}

clickCard()
```

CSS:

``` css
td{
    position:relative;
    width: 200px;
    height: 300px;
    margin: 20px ;
    border-radius: 50% / 10%; /*creates rounded shape */
    color: white;
    text-align: center;
    background-image: url("img/cardback.jpg");
    background-size: contain;
    background-repeat: no-repeat;
}
```

HTML:

``` html
  <main>

<table>
    <tr class = "row">
        <td> </td>
        <td> </td>
        <td> </td>
        <td> </td>
    <tr class ="row">
        <td> </td>
        <td> </td>
        <td> </td>
        <td> </td>

    </tr>
    </tr>

</table>

</main>
```
