### ISSUE TITLE
I need help with table spacing

### ISSUE THREAD

**Issue by Thesheik** [ga-dc/project1#52]
Already created table format into html but I am having issues getting space in between them. 
I tried using <br> tag but it is not working.

**Comment by jshawl** [comment]
what if you try using padding? here's an example: http://codepen.io/jshawl/pen/bdKEvR

**Comment by jshawl** [comment]
you can add a border with:

``` css
table, td, th{
  border: 1px solid black;
}
```
